// Error codes
export const ERROR_CODES = {
  INVALID_INPUT: 'INVALID_INPUT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SIGNUP_FAILED: 'SIGNUP_FAILED',
  SIGNIN_FAILED: 'SIGNIN_FAILED',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  CREATE_VAULT_ERROR: 'CREATE_VAULT_ERROR',
  GET_VAULT_ERROR: 'GET_VAULT_ERROR',
  LIST_VAULTS_ERROR: 'LIST_VAULTS_ERROR',
  UPDATE_VAULT_ERROR: 'UPDATE_VAULT_ERROR',
  DELETE_VAULT_ERROR: 'DELETE_VAULT_ERROR',
  GET_MEMBERS_ERROR: 'GET_MEMBERS_ERROR',
  REMOVE_MEMBER_ERROR: 'REMOVE_MEMBER_ERROR',
  CREATE_INVITE_ERROR: 'CREATE_INVITE_ERROR',
  ACCEPT_INVITE_ERROR: 'ACCEPT_INVITE_ERROR',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  CANNOT_REMOVE_LAST_OWNER: 'CANNOT_REMOVE_LAST_OWNER',
  CREATE_CONTENT_ERROR: 'CREATE_CONTENT_ERROR',
  GET_CONTENT_ERROR: 'GET_CONTENT_ERROR',
  LIST_CONTENT_ERROR: 'LIST_CONTENT_ERROR',
  UPDATE_CONTENT_ERROR: 'UPDATE_CONTENT_ERROR',
  DELETE_CONTENT_ERROR: 'DELETE_CONTENT_ERROR',
  ADD_TAGS_ERROR: 'ADD_TAGS_ERROR',
  CREATE_TAG_ERROR: 'CREATE_TAG_ERROR',
  GET_TAGS_ERROR: 'GET_TAGS_ERROR',
  UPDATE_TAG_ERROR: 'UPDATE_TAG_ERROR',
  DELETE_TAG_ERROR: 'DELETE_TAG_ERROR',
  NO_UPDATES: 'NO_UPDATES',
  TRANSCRIPTION_ERROR: 'TRANSCRIPTION_ERROR',
  EMBEDDING_ERROR: 'EMBEDDING_ERROR',
  STORE_EMBEDDING_ERROR: 'STORE_EMBEDDING_ERROR',
  GET_EMBEDDING_ERROR: 'GET_EMBEDDING_ERROR',
  DELETE_EMBEDDING_ERROR: 'DELETE_EMBEDDING_ERROR',
  SIMILARITY_SEARCH_ERROR: 'SIMILARITY_SEARCH_ERROR',
  BUILD_GRAPH_ERROR: 'BUILD_GRAPH_ERROR',
  GET_RELATED_ITEMS_ERROR: 'GET_RELATED_ITEMS_ERROR',
  CHAT_ERROR: 'CHAT_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  VAULT_NOT_FOUND: 'VAULT_NOT_FOUND',
  CONTENT_NOT_FOUND: 'CONTENT_NOT_FOUND',
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_VALIDATION_ERROR: 'TOKEN_VALIDATION_ERROR',
  SESSION_CREATION_FAILED: 'SESSION_CREATION_FAILED',
} as const;

// HTTP status codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

// Cache TTLs (in milliseconds)
export const CACHE_TTL = {
  VAULT: 5 * 60 * 1000, // 5 minutes
  TAGS: 5 * 60 * 1000, // 5 minutes
  GRAPH: 10 * 60 * 1000, // 10 minutes
  USER_PERMISSIONS: 10 * 60 * 1000, // 10 minutes
} as const;

// Pagination defaults
export const PAGINATION = {
  DEFAULT_LIMIT: 50,
  MAX_LIMIT: 100,
  DEFAULT_OFFSET: 0,
} as const;

// Embedding configuration
export const EMBEDDING = {
  DIMENSION: 768,
  DEFAULT_THRESHOLD: 0.8,
  TOP_K: 10,
} as const;

// Retry configuration
export const RETRY = {
  MAX_RETRIES: 3,
  INITIAL_DELAY_MS: 100,
  MAX_DELAY_MS: 10000,
  BACKOFF_MULTIPLIER: 2,
} as const;

// Rate limiting
export const RATE_LIMIT = {
  AUTH_WINDOW_MS: 15 * 60 * 1000, // 15 minutes
  AUTH_MAX_REQUESTS: 5,
  API_WINDOW_MS: 15 * 60 * 1000, // 15 minutes
  API_MAX_REQUESTS: 100,
} as const;

// Invitation configuration
export const INVITATION = {
  EXPIRATION_DAYS: 7,
} as const;

// Content types
export const CONTENT_TYPES = {
  AUDIO: 'audio',
  IMAGE: 'image',
  LINK: 'link',
} as const;

// Roles
export const ROLES = {
  OWNER: 'owner',
  MEMBER: 'member',
} as const;
